openapi: 3.0.0
info:
  title: eShop API
  version: 1.0.0
  description: REST API for eShop project - types, products, reviews, auth

servers:
  - url: http://localhost:3000

paths:
  # ----------------- TYPES -----------------
  /api/types:
    get:
      summary: Get all types
      responses:
        '200':
          description: List of types
        '500':
          description: Internal server error
    post:
      summary: Create a new type
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                image:
                  type: string
      responses:
        '201':
          description: Type created
        '400':
          description: Name required
        '403':
          description: Forbidden (requires admin)
        '409':
          description: Duplicate type name
        '500':
          description: Internal server error

  /api/types/{id}:
    get:
      summary: Get a single type
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Type object
        '404':
          description: Type not found
        '500':
          description: Internal server error
    put:
      summary: Update a type
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                image:
                  type: string
      responses:
        '200':
          description: Type updated
        '400':
          description: Name required
        '403':
          description: Forbidden (requires admin)
        '404':
          description: Type not found
        '500':
          description: Internal server error
    delete:
      summary: Delete a type
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Type deleted
        '403':
          description: Forbidden (requires admin)
        '404':
          description: Type not found
        '500':
          description: Internal server error

  /api/types/{id}/products:
    get:
      summary: Get all products of a specific type
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Products for the type
        '404':
          description: Type not found
        '500':
          description: Internal server error

  /api/types/{typeId}/products/{productId}/reviews:
    get:
      summary: Get all reviews of a product under a specific type
      parameters:
        - in: path
          name: typeId
          schema:
            type: integer
          required: true
        - in: path
          name: productId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: List of reviews
        '404':
          description: Type or product not found
        '500':
          description: Internal server error

  # ----------------- PRODUCTS -----------------
  /api/products:
    get:
      summary: Get all products
      responses:
        '200':
          description: List of products
        '500':
          description: Internal server error
    post:
      summary: Create a new product
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - brand
                - name
                - type_id
                - price
              properties:
                brand:
                  type: string
                name:
                  type: string
                type_id:
                  type: integer
                price:
                  type: number
                description:
                  type: string
                image:
                  type: string
      responses:
        '201':
          description: Product created
        '400':
          description: Invalid payload
        '403':
          description: Forbidden (requires admin)
        '409':
          description: Product already exists
        '500':
          description: Internal server error

  /api/products/{id}:
    get:
      summary: Get a single product
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Product object
        '404':
          description: Product not found
        '500':
          description: Internal server error
    put:
      summary: Update a product
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - brand
                - name
                - type_id
                - price
              properties:
                brand:
                  type: string
                name:
                  type: string
                type_id:
                  type: integer
                price:
                  type: number
                description:
                  type: string
                image:
                  type: string
      responses:
        '200':
          description: Product updated
        '400':
          description: Invalid input data
        '403':
          description: Forbidden (requires admin)
        '404':
          description: Product not found
        '500':
          description: Internal server error
    delete:
      summary: Delete a product
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Product deleted
        '403':
          description: Forbidden (requires admin)
        '404':
          description: Product not found
        '500':
          description: Internal server error

  # ----------------- REVIEWS -----------------
  /api/reviews:
    get:
      summary: Get all reviews
      responses:
        '200':
          description: List of reviews
        '500':
          description: Internal server error
    post:
      summary: Create a new review
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - product_id
                - rating
              properties:
                product_id:
                  type: integer
                rating:
                  type: integer
                comment:
                  type: string
      responses:
        '201':
          description: Review created
        '400':
          description: Invalid payload
        '500':
          description: Internal server error

  /api/reviews/{id}:
    get:
      summary: Get a single review
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Review object
        '404':
          description: Review not found
        '500':
          description: Internal server error
    put:
      summary: Update a review
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - rating
                - comment
              properties:
                rating:
                  type: integer
                comment:
                  type: string
                user_id:
                  type: integer
                  description: Optional; must match existing user_id. Cannot change.
      responses:
        '200':
          description: Review updated
        '400':
          description: Invalid payload or user_id mismatch
        '403':
          description: Forbidden (not owner/admin)
        '404':
          description: Review not found
        '500':
          description: Internal server error
    delete:
      summary: Delete a review
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Review deleted
        '403':
          description: Forbidden (not owner/admin)
        '404':
          description: Review not found
        '500':
          description: Internal server error

  # ----------------- AUTH -----------------
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        '201':
          description: User registered
        '400':
          description: Missing fields
        '409':
          description: Email already exists
        '500':
          description: Internal server error

  /api/auth/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Returns access token
        '401':
          description: Invalid credentials
        '500':
          description: Internal server error

  /api/auth/refresh:
    post:
      summary: Refresh JWT access token
      responses:
        '200':
          description: New access token
        '401':
          description: Invalid or missing refresh token
        '403':
          description: Session expired or invalid
        '500':
          description: Internal server error

  /api/auth/logout:
    post:
      summary: Logout user
      responses:
        '200':
          description: Logged out
        '500':
          description: Internal server error

  /api/auth/me:
    get:
      summary: Get current logged-in user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current user info
        '404':
          description: User not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
